apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: httpbin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpbin
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
